### ISSUE TITLE
Update Ionut Balosin

### ISSUE THREAD

**Issue by ionutbalosin** [aalmiray/java-champions#327]
Hi Andres,

Could I kindly ask you to update my profile to the following? 

```
  - name: Ionut Balosin
    year: 2025
    country:
      nomination: Austria
    city: Vienna
    social:
      twitter: https://twitter.com/ionutbalosin
      linkedin: https://www.linkedin.com/in/ionutbalosin/
      website: https://ionutbalosin.com/
      mastodon: https://mastodon.social/@ionutbalosin
      bluesky: https://bsky.app/profile/ionutbalosin.bsky.social
      github: https://github.com/ionutbalosin
    avatar: img/avatars/ionutbalosin.png
```

I tried to create a pull request, but it seems I don't have the necessary permissions to push a new branch.

Thanks in advance for your help!

Thanks
Ionut Balosin
